### ISSUE TITLE
Support for VOD quality selector plugin

### ISSUE THREAD

**Issue by vascofg** [gradeup/react-flow-player#1]
Hey, great work!
Could you please add support for this plugin? https://flowplayer.com/docs/player/plugins.html#vod-quality-selector
Here is an example:
http://demos.flowplayer.org/scripting/qsel.html

**Comment by pc9** [comment]
Hey @vascofg 
just published a new version which now accepts new props (vodQualitySelectorSrc, qualities, defaultQuality, defaultQuality) to enable VOD quality selection.

Let us know in case of any problem,
Thanks.

**Comment by vascofg** [comment]
It's working great! I wonder if it would make sense to add a boolean prop to enable loading the plugin like you have for HLS.

**Comment by vascofg** [comment]
I'm currently working on some improvements for the module, will submit a pull request shortly.
