### ISSUE TITLE
how to play rtmp?

### ISSUE THREAD

**Issue by sunnyYang07** [gradeup/react-flow-player#11]
hello, please write a demo for rtmp, thank you!!!!

**Comment by AmanAgarwal041** [comment]
`
<ReactFlowPlayer
	sources=[{
	  type: 'video/flash',
	  src: "rtmp url",
	}]
        rtmp="rtmp url"
	playerInitScript="https://releases.flowplayer.org/7.2.4/commercial/flowplayer.min.js"
	playerId="reactFlowPlayer"
	title="title"
	licenseKey=""
/>
`
